version: '3'
services:
  app1:
    container_name: isu-runner1
    build: ./app
    tty: true
    ports: 
      - "3000:80"
    volumes:
      # - ./app:/home/app
      - ./images:/home/isucon9-qualify/initial-data/images:cached
      - ./upload:/home/isucon9-qualify/webapp/public/upload:cached
    networks:
      app:
        ipv4_address: 172.30.0.2
  app2:
    container_name: isu-runner2
    build: ./app
    tty: true
    volumes:
      # - ./app:/home/app
      - ./images:/home/isucon9-qualify/initial-data/images:cached
      - ./upload:/home/isucon9-qualify/webapp/public/upload:cached
    networks:
      app:
        ipv4_address: 172.30.0.3
  app3:
    container_name: isu-runner3
    build: ./app
    tty: true
    volumes:
      # - ./app:/home/app
      - ./images:/home/isucon9-qualify/initial-data/images:cached
      - ./upload:/home/isucon9-qualify/webapp/public/upload:cached
    networks:
      app:
        ipv4_address: 172.30.0.4
networks:
  app:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24

