FROM ubuntu:18.04
EXPOSE 3306
RUN apt update
RUN apt upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:longsleep/golang-backports -y
RUN apt update
RUN apt install git make unzip curl docker mysql-server mysql-client golang -y
WORKDIR /home
RUN mkdir app
RUN mkdir isucon9-qualify
# CMD sh app/init.sh