FROM ubuntu:18.04
RUN apt update
RUN apt upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:longsleep/golang-backports -y
RUN apt update
RUN apt install git make unzip curl mysql-server mysql-client golang -y
# RUN curl -fsSL https://get.docker.com -o get-docker.sh
# RUN sh get-docker.sh
WORKDIR /home
RUN mkdir app
RUN mkdir isucon9-qualify
# CMD sh app/init.sh